services:
  app:
    build:
      context: .  # Build from the root directory
      dockerfile: Dockerfile  # The Dockerfile in the root
    ports:
      - "8000:8000"  # Back-end port
      - "3000:3000"  # Front-end port (if served separately)
    restart: always